### ISSUE TITLE
Suggestion: Easy Copy/Paste Server IP and Port?

### ISSUE THREAD

**Issue by wykydtronik** [DayZServerApp/DayZServer#6]
Hello Dev,

I am regularly using DayZServer app to keep track of recent servers. It's handy to avoid stream snipers when you're with a group by simply staying offline on Steam to prevent people from looking you up on third party sites like GameTracker, or even Steam Friends lists. I think it would be handy to have the ability to quickly copy/paste server ip and port so that you can paste it to your squad/clan members in comms (like TeamSpeak, Ventrilo, etc).

Please consider this feature, thanks for providing an awesome tool to the DayZ community. <3

-Kaichi

**Comment by multimediaxman** [comment]
Nice use of the app! Thanks for the feature request.  We have added this feature to the source and are now testing it. Should have a new build out on 6.13.2015

**Comment by getsomeual** [comment]
Wish this was still getting love

**Comment by multimediaxman** [comment]
The app has finally gotten an update! [https://github.com/DayZServerApp/DayZServer/releases](url)

**Comment by multimediaxman** [comment]
Implement Copy/Paste Server IP and Port
